### PR TITLE
Circleci testing

### PR DESCRIPTION
**Pull request by drazisil**

### CODE REVIEW

**Comment by drazisil** [comment]
Currently failing 

Error binding to P2P port: Couldn't listen on any:29333: [Errno 98] Address already in use.

**Comment by drazisil** [comment]
@forrestv

Sorry to bother you, but do you have any ideas why https://circleci.com/gh/drazisil/p2pool/32 is failing? No rush.

**Comment by forrestv** [comment]
Some of the tests require a local P2Pool node or bitcoin node running. Not
really ideal for this... Also, I noticed a failure due to ltc_scrypt not
being built/installed.

**Comment by drazisil** [comment]
Added ability to use regtest, and launching bitcoin.

However, it seems it's getting banned due to sending the same TX twice

```
2015-11-03 19:53:46.681009 Advertising for incoming connections
2015-11-03 19:53:47.282571 Peer sent entire transaction 12e30a58a5822f7398f0177ab57356d640ce8e10a0f2d15721cc451e68b5c97f that was already received
2015-11-03 19:53:47.315001 Peer sent entire transaction f22e3acdb93b496893dd544f461c31f5c40b41b645bd3ea97f111fce938e2d0a that was already received
2015-11-03 19:53:47.335903 Peer 127.0.0.1:47367 misbehaving, will drop and ban. Reason: too much transaction data stored
2015-11-03 19:53:47.335994 Bad peer banned: ('127.0.0.1', 47367)
2015-11-03 19:53:47.336596 Lost peer 127.0.0.1:47367 - Connection was aborted locally, using.
2015-11-03 19:53:47.336739 Peer connection lost: ('127.0.0.1', 47367) [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionAborted'>: Connection was aborted locally, using.
```
My question is, how is this possible, unless p2pool is somehow storing the tx in a file that's not getting cleared? It passes on local, which makes even less sense.

**Comment by drazisil** [comment]
https://circleci.com/gh/drazisil/p2pool/137

So now it looks like it's getting rejected/banned due to share being 'too long'

https://circle-artifacts.com/gh/drazisil/p2pool/137/artifacts/0/tmp/circle-artifacts.iCDAfS7/stderr_python_14762.txt

I suspect it's because It's testing mainnet shares against regnet, but I'm not sure how to isolate it at this time.

**Comment by drazisil** [comment]
This isn't syncing, I need a new one

**Pull request closed without merging**
